-- noethervim-tex.accent_spell.decoder spec.

local decoder = require("noethervim-tex.accent_spell.decoder")

describe("decoder.decode", function()
  before_each(function()
    decoder._reset()
  end)

  describe("bare punctuation accents", function()
    it("grave \\`a -> à", function()
      assert.are.equal("à", decoder.decode("\\`a"))
    end)
    it("acute \\'e -> é", function()
      assert.are.equal("é", decoder.decode("\\'e"))
    end)
    it("circumflex \\^o -> ô", function()
      assert.are.equal("ô", decoder.decode("\\^o"))
    end)
    it('umlaut \\"a -> ä', function()
      assert.are.equal("ä", decoder.decode('\\"a'))
    end)
    it("tilde \\~n -> ñ", function()
      assert.are.equal("ñ", decoder.decode("\\~n"))
    end)
    it("dot \\.a -> ȧ", function()
      assert.are.equal("ȧ", decoder.decode("\\.a"))
    end)
    it("macron \\=a -> ā", function()
      assert.are.equal("ā", decoder.decode("\\=a"))
    end)
    it("works on uppercase letters", function()
      assert.are.equal("Ä", decoder.decode('\\"A'))
      assert.are.equal("É", decoder.decode("\\'E"))
    end)
  end)

  describe("braced punctuation accents", function()
    it('\\"{a} -> ä', function()
      assert.are.equal("ä", decoder.decode('\\"{a}'))
    end)
    it("\\'{e} -> é", function()
      assert.are.equal("é", decoder.decode("\\'{e}"))
    end)
    it("matches inner letter, not the brace chars", function()
      assert.are.equal("ö", decoder.decode('\\"{o}'))
      assert.are.equal("Ö", decoder.decode('\\"{O}'))
    end)
  end)

  describe("letter accents (require braces)", function()
    it("cedilla \\c{c} -> ç", function()
      assert.are.equal("ç", decoder.decode("\\c{c}"))
    end)
    it("hungarian \\H{o} -> ő", function()
      assert.are.equal("ő", decoder.decode("\\H{o}"))
    end)
    it("ogonek \\k{a} -> ą", function()
      assert.are.equal("ą", decoder.decode("\\k{a}"))
    end)
    it("ring \\r{a} -> å", function()
      assert.are.equal("å", decoder.decode("\\r{a}"))
    end)
    it("breve \\u{a} -> ă", function()
      assert.are.equal("ă", decoder.decode("\\u{a}"))
    end)
    it("caron \\v{c} -> č", function()
      assert.are.equal("č", decoder.decode("\\v{c}"))
    end)
    it("bare letter accent (no braces) is invalid", function()
      assert.is_nil(decoder.decode("\\Ho"))
      assert.is_nil(decoder.decode("\\vc"))
    end)
  end)

  describe("dotless letters", function()
    it("standalone \\i -> ı", function()
      assert.are.equal("ı", decoder.decode("\\i"))
    end)
    it("standalone \\j -> ȷ", function()
      assert.are.equal("ȷ", decoder.decode("\\j"))
    end)
    it('accented dotless \\"\\i -> ï', function()
      assert.are.equal("ï", decoder.decode('\\"\\i'))
    end)
    it('braced accented dotless \\"{\\i} -> ï', function()
      assert.are.equal("ï", decoder.decode('\\"{\\i}'))
    end)
    it("acute over dotless \\'\\i -> í", function()
      assert.are.equal("í", decoder.decode("\\'\\i"))
    end)
  end)

  describe("real-world names round-trip", function()
    it("K\\\"ahler -> Kähler", function()
      assert.are.equal("Kähler", decoder.decode('K\\"ahler'))
    end)
    it('K\\"{a}hler -> Kähler', function()
      assert.are.equal("Kähler", decoder.decode('K\\"{a}hler'))
    end)
    it('H\\"older -> Hölder', function()
      assert.are.equal("Hölder", decoder.decode('H\\"older'))
    end)
    it("Erd\\H{o}s -> Erdős", function()
      assert.are.equal("Erdős", decoder.decode("Erd\\H{o}s"))
    end)
    it("Poincar\\'e -> Poincaré", function()
      assert.are.equal("Poincaré", decoder.decode("Poincar\\'e"))
    end)
    it('Schr\\"odinger -> Schrödinger', function()
      assert.are.equal("Schrödinger", decoder.decode('Schr\\"odinger'))
    end)
    it('M\\"obius -> Möbius', function()
      assert.are.equal("Möbius", decoder.decode('M\\"obius'))
    end)
    it("B\\'ezier -> Bézier", function()
      assert.are.equal("Bézier", decoder.decode("B\\'ezier"))
    end)
    it("Fr\\'echet -> Fréchet", function()
      assert.are.equal("Fréchet", decoder.decode("Fr\\'echet"))
    end)
    it("Caf\\'e -> Café", function()
      assert.are.equal("Café", decoder.decode("Caf\\'e"))
    end)
    it('na\\"ive -> naïve', function()
      assert.are.equal("naïve", decoder.decode('na\\"ive'))
    end)
    it("\\'etal\\'e -> étalé (multi-accent)", function()
      assert.are.equal("étalé", decoder.decode("\\'etal\\'e"))
    end)
    it("r\\'esum\\'e -> résumé (multi-accent)", function()
      assert.are.equal("résumé", decoder.decode("r\\'esum\\'e"))
    end)
    it("fa\\c{c}ade -> façade", function()
      assert.are.equal("façade", decoder.decode("fa\\c{c}ade"))
    end)
  end)

  describe("plain text", function()
    it("returns input unchanged when there are no backslashes", function()
      assert.are.equal("Kahler", decoder.decode("Kahler"))
      assert.are.equal("hello world", decoder.decode("hello world"))
    end)
    it("returns empty string for empty input", function()
      assert.are.equal("", decoder.decode(""))
    end)
    it("returns nil for nil input untouched", function()
      assert.is_nil(decoder.decode(nil))
    end)
  end)

  describe("conservative nil for unrecognised input", function()
    it("returns nil for unknown macro \\hat", function()
      assert.is_nil(decoder.decode("\\hat{x}"))
    end)
    it("returns nil for trailing backslash", function()
      assert.is_nil(decoder.decode("foo\\"))
    end)
    it("returns nil for unmatched brace", function()
      assert.is_nil(decoder.decode('K\\"{a'))
    end)
    it("returns nil for accent over non-letter", function()
      assert.is_nil(decoder.decode('\\"5'))
    end)
    it("returns nil for accent + multi-char braced argument", function()
      assert.is_nil(decoder.decode('\\"{ab}'))
    end)
    it("returns nil for accent over unsupported letter", function()
      -- \"d (umlaut over d) is not defined in vimtex's table; only \v{d} is.
      assert.is_nil(decoder.decode('\\"d'))
    end)
    it("returns nil if any embedded accent is unsupported", function()
      -- The first accent decodes; the second doesn't -> whole token nil.
      assert.is_nil(decoder.decode("Caf\\'\\hat{x}"))
    end)
  end)

  describe("M.extend", function()
    it("registers a new (accent, letter) pair", function()
      assert.is_nil(decoder.decode('\\"d'))
      decoder.extend({ ['"d'] = "CUSTOM" })
      assert.are.equal("CUSTOM", decoder.decode('\\"d'))
    end)
    it("can override an existing entry", function()
      decoder.extend({ ['"a'] = "OVERRIDE" })
      assert.are.equal("OVERRIDE", decoder.decode('\\"a'))
    end)
    it("accepts an empty / nil table", function()
      assert.has_no.errors(function() decoder.extend({}) end)
      assert.has_no.errors(function() decoder.extend(nil) end)
    end)
  end)

  describe("M.encode (Unicode -> LaTeX)", function()
    it("encodes proper nouns to bare punct accents", function()
      assert.are.equal("K\\\"ahler",      decoder.encode("Kähler"))
      assert.are.equal("H\\\"older",      decoder.encode("Hölder"))
      assert.are.equal("Schr\\\"odinger", decoder.encode("Schrödinger"))
      assert.are.equal("M\\\"obius",      decoder.encode("Möbius"))
      assert.are.equal("Poincar\\'e",     decoder.encode("Poincaré"))
      assert.are.equal("B\\'ezier",       decoder.encode("Bézier"))
    end)
    it("encodes letter accents with required braces", function()
      assert.are.equal("Erd\\H{o}s",  decoder.encode("Erdős"))
      assert.are.equal("fa\\c{c}ade", decoder.encode("façade"))
    end)
    it("preserves multi-accent words", function()
      assert.are.equal("r\\'esum\\'e", decoder.encode("résumé"))
      assert.are.equal("\\'etal\\'e",  decoder.encode("étalé"))
    end)
    it("passes ASCII text through unchanged", function()
      assert.are.equal("hello world", decoder.encode("hello world"))
      assert.are.equal("Kahler",      decoder.encode("Kahler"))
      assert.are.equal("",            decoder.encode(""))
    end)
    it("encodes standalone dotless letters", function()
      assert.are.equal("\\i", decoder.encode("ı"))
      assert.are.equal("\\j", decoder.encode("ȷ"))
    end)
    it("prefers dotted-letter form for ï (so \"i not \"\\i)", function()
      assert.are.equal("na\\\"ive", decoder.encode("naïve"))
    end)
    it("round-trips: decode . encode = identity", function()
      local raws = {
        'K\\"ahler', "Erd\\H{o}s", "Poincar\\'e", "Schr\\\"odinger",
        "fa\\c{c}ade", "r\\'esum\\'e", "\\'etal\\'e", "M\\\"obius",
        "Caf\\'e",
      }
      for _, raw in ipairs(raws) do
        assert.are.equal(raw, decoder.encode(decoder.decode(raw)))
      end
    end)
    it("respects extend()-added entries in inverse", function()
      -- Pick a codepoint guaranteed not to collide with vimtex's table
      -- (★ is U+2605 -- not an accented latin letter, so the inverse
      -- table doesn't already know about it).
      decoder.extend({ ['"q'] = "★" })
      assert.are.equal('\\"q', decoder.encode("★"))
    end)
  end)

  describe("vimtex table fidelity", function()
    -- Spot-check: every accent the upstream table defines for at
    -- least one letter must produce a non-empty Unicode result.
    -- (Catches table-corruption regressions.)
    local samples = {
      { '\\`a',     "à" },
      { "\\'a",     "á" },
      { "\\^a",     "â" },
      { '\\"a',     "ä" },
      { "\\~a",     "ã" },
      { "\\.a",     "ȧ" },
      { "\\=a",     "ā" },
      { "\\c{c}",   "ç" },
      { "\\H{o}",   "ő" },
      { "\\k{a}",   "ą" },
      { "\\r{a}",   "å" },
      { "\\u{a}",   "ă" },
      { "\\v{c}",   "č" },
    }
    for _, pair in ipairs(samples) do
      local raw, expected = pair[1], pair[2]
      it("decodes " .. raw .. " -> " .. expected, function()
        assert.are.equal(expected, decoder.decode(raw))
      end)
    end
  end)
end)
